### ISSUE TITLE
Unexpected polyfill

### ISSUE THREAD

**Issue by egoist** [anydown/vue-spreadsheet-lite#2]
Bili 3.0.5 fixed the error you mentioned on twitter, however if you use the babelrc from vue-cli, you will get following output code in `dist/vue-spreadsheet-lite.cjs.js`:

```js
'use strict';

function _interopDefault (ex) { return (ex && (typeof ex === 'object') && 'default' in ex) ? ex['default'] : ex; }

require('core-js/modules/es6.function.name');
require('bootstrap/dist/css/bootstrap-reboot.min.css');
var Vue = _interopDefault(require('vue'));
```

This will lead to error since you don't have `core-js` as a dependency.

`@vue/babel-preset-app` [automatically add polyfills](https://github.com/vuejs/vue-cli/blob/ba5a3750f59b881c4350c9beee5427ec49a5a4ee/packages/%40vue/babel-preset-app/index.js#L20) which is good for application but you don't need this while building a library.

Here're two solutions:

1. disable polyfill. update your `.babelrc` to as follows:

```js
{
  "presets": [
    ["@vue/app", {"useBuiltIns": false}]
  ]
}
```
2. disable `.babelrc`: simply use `--no-babel.babelrc` again

**Comment by hashrock** [comment]
I just applied your first proposal because it seems not need polyfills in examples in this repo. Thank you a lot!

https://github.com/anydown/vue-spreadsheet-lite/commit/77d9af777ebecf7be8a5d329aaf6d4b957fd1ffd
